void ip2str(int n, unsigned char str[]);
int str2ip(unsigned char str[]);
int strLen(char str[]);
void strConcat(char str1[], char str2[]);
void bubble(int *arr,int len);
void reverseArr(int *arr,int len);
int getSecondMaxItem(int *arr,int len);
void reverseEnglishString(char *str);
void reverseChineseString(char *str);
void transmitArgumentsOftwoDimensionArray(int (*p)[3],int i,int j);
void mystrcat(char *s1,const char *s2);
char *mystrchr(char *s,char c);
int ope(int (*p)(int,int),int a,int b);
void print_str(char *c);